#!/usr/bin/bash

# Script version
VER=35
# Allows to version the manager based on its contents.
# Bump VER whenever we want to trigger a run explicitly event though the script is not changed.
SCRIPT_HASH=$(tr -d '[:space:]' <"$0" | sha256sum | cut -d ' ' -f 1)
VER="$VER-$SCRIPT_HASH"
VER_FILE="/etc/bazzite/flatpak_manager_version"
VER_RAN=$(cat $VER_FILE)
IMAGE_INFO="/usr/share/ublue-os/image-info.json"
IMAGE_NAME=$(jq -r '."image-name"' < $IMAGE_INFO)
BASE_IMAGE_NAME=$(jq -r '."base-image-name"' < $IMAGE_INFO)

# IMAGE IDENTIFIERS
KNOWN_IMAGE_NAME_FILE="/etc/bazzite/flatpak_manager_image_name"
KNOWN_IMAGE_NAME=$(cat $KNOWN_IMAGE_NAME_FILE)

# Run script if updated
if [[ -f $VER_FILE && $VER = $VER_RAN ]]; then
  if [[ -f $KNOWN_IMAGE_NAME_FILE ]]; then
    if [[ $IMAGE_NAME = $KNOWN_IMAGE_NAME ]]; then
      echo "Flatpak manager v$VER has already ran. Exiting..."
      exit 0
    fi
  fi
fi

# Ensure Flathub is enabled
flatpak remote-add --if-not-exists --system flathub /etc/flatpak/remotes.d/flathub.flatpakrepo || :
flatpak remote-modify --system --enable flathub || :

# Disable fedora flatpak remote
flatpak remote-modify --disable fedora || :
flatpak remote-modify --disable fedora-testing || :

# Filter out references from Flathub remote
if [[ -f /usr/share/ublue-os/flatpak-blocklist ]]; then
  flatpak remote-modify --system --filter=/usr/share/ublue-os/flatpak-blocklist flathub
fi

# Remove Bazzite Portal Flatpak Leftovers if present
flatpak uninstall --system --assumeyes com.github.yafti.gtk || :
flatpak uninstall --system --assumeyes io.github.xxjsonderuloxx.yafti-gtk || :

# Flatpak theming support
flatpak override \
  --filesystem=xdg-config/gtk-4.0:ro \
  --filesystem=xdg-config/gtk-3.0:ro

# Fix printing on LibreOffice
flatpak override \
  --system \
  --socket=cups \
  --socket=session-bus \
  org.libreoffice.LibreOffice

# Allow MangoHUD config for Flatpaks
flatpak override \
  --filesystem=xdg-config/MangoHud:create \
  --filesystem=xdg-config/vkBasalt:create

# Fix permissions for XIV Launcher
flatpak override \
  --device=dri \
  dev.goats.xivlauncher

# Fix permissions for Protontricks
flatpak override \
  --filesystem=~/.local/share/Steam \
  --filesystem=/var/mnt \
  --filesystem=/run/media \
  com.github.Matoking.protontricks

# Allow smartphone's passkey for chrome browsers
for app in \
    com.brave.Browser \
    com.google.Chrome \
    io.github.ungoogled_software.ungoogled_chromium
do
    flatpak override --system-talk-name=org.bluez $app
done && unset -v app

# Unpin known runtimes added by older ISOs and remove unused runtimes
xargs -L 1 -a /usr/share/ublue-os/bazzite-flatpak-eol flatpak pin --system --remove &>/dev/null || :
flatpak uninstall --system --unused --assumeyes || :

mkdir -p /etc/bazzite
echo $VER > $VER_FILE
echo $IMAGE_NAME > $KNOWN_IMAGE_NAME_FILE
