name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * 0" # 0015 UTC on Sundays
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Delete Images Older Than 90 Days
        uses: step-security/ghcr-cleanup-action@0d2f9c9d0a80b38158c52e709ef7617b48cc65cc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: bazzite, bazzite-gnome, bazzite-deck, bazzite-deck-gnome, bazzite-deck-nvidia, bazzite-deck-nvidia-gnome, bazzite-nvidia, bazzite-gnome-nvidia, bazzite-nvidia-open, bazzite-gnome-nvidia-open
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
